---
- name: HyperRegistry | Find ingress Service's IP
  command: "{{ bin_dir }}/kubectl get services -n {{ ingress_nginx_namespace }} {{ ingress_nginx_namespace }}-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}'"
  changed_when: false
  register: "ingress_status"

- name: HyperRegistry | Set ingress Service IP
  set_fact:
    hyperregistry_ingress_nginx_ip: "{{ ingress_status.stdout }}"
