---
- name: HyperRegistry | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/hyperregistry"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: inventory_hostname == groups['kube_control_plane'][0]

- name: HyperRegistry | Get ingress IP
  include_tasks: "ingress_ip.yml"
  when: hyperregistry_ingress_nginx_ip | length == 0

- name: HyperRegistry | Create values.yml
  template:
    src: "{{ item }}.j2"
    dest: "{{ kube_config_dir }}/addons/hyperregistry/{{ item }}"
  with_items: ["values.yml"]
  when: inventory_hostname == groups['kube_control_plane'][0]

- name: HyperRegistry | Install HyperRegistry Chart
  vars:
    - chart: "{{ files_repo | regex_replace('^file://', '') }}/hyperregistry-{{ hyperregistry_version }}.tgz"
  shell: |
    /usr/local/bin/helm install hyperregistry {{ chart }} -n {{ hyperregistry_namespace }} --create-namespace -f {{ kube_config_dir }}/addons/hyperregistry/values.yml
  when: inventory_hostname == groups['kube_control_plane'][0]
