---
# tasks file for efk
- name: EFK | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/efk"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: EFK | Generate Manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/efk/{{ item.file }}"
  with_items:
    - { name: efk-namespace, file: efk-namespace.yml }
    - { name: efk-elasticsearch-statefulset, file: efk-elasticsearch-statefulset.yml }
    - { name: efk-kibana-deployment, file: efk-kibana-deployment.yml }
    - { name: efk-fluentd-daemonset, file: efk-fluentd-daemonset.yml }
  register: efk_manifests
  when: inventory_hostname == groups['kube_control_plane'][0]

- name: EFK | Apply Manifests
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/addons/efk/{{ item.item.file }}"
    state: "latest"
    wait: true
  with_items:
    - "{{ efk_manifests.results }}"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
  loop_control:
    label: "{{ item.item.file }}"
