---
cicd_enabled: true
cicd_ingress_class: nginx-shd
cicd_ingress_host: ''
cicd_external_host: ''
cicd_webhook_service_type: 'ClusterIP'

## cicd images
cicd_git_image_repo: "{{ docker_image_repo }}/alpine/git"
cicd_git_image_tag: "1.0.30"
cicd_operator_image_repo: "{{ docker_image_repo }}/tmaxcloudck/cicd-operator"
cicd_operator_image_tag: "v0.3.2"
cicd_blocker_image_repo: "{{ docker_image_repo }}/tmaxcloudck/cicd-blocker"
cicd_blocker_image_tag: "v0.3.2"
cicd_tekton_pipeline_operator_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/pipeline/cmd/controller"
cicd_tekton_pipeline_operator_image_tag: "v0.26.0"
cicd_tekton_kubeconfig_writer_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter"
cicd_tekton_kubeconfig_writer_image_tag: "v0.26.0"
cicd_tekton_git_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init"
cicd_tekton_git_image_tag: "v0.26.0"
cicd_tekton_entrypoint_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint"
cicd_tekton_entrypoint_image_tag: "v0.26.0"
cicd_tekton_nop_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/pipeline/cmd/nop"
cicd_tekton_nop_image_tag: "v0.26.0"
cicd_tekton_digest_exporter_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter"
cicd_tekton_digest_exporter_image_tag: "v0.26.0"
cicd_tekton_pr_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init"
cicd_tekton_pr_image_tag: "v0.26.0"
cicd_tekton_gsutil_image_repo: "{{ gcr_image_repo }}/google.com/cloudsdktool/cloud-sdk"
cicd_tekton_gsutil_image_sha: "sha256:27b2c22bf259d9bc1a291e99c63791ba0c27a04d2db0a43241ba0f1f20f4067f"
cicd_tekton_shell_image_repo: "{{ gcr_image_repo }}/distroless/base"
cicd_tekton_shell_image_sha: "sha256:aa4fd987555ea10e1a4ec8765da8158b5ffdfef1e72da512c7ede509bc9966c4"
cicd_tekton_pipeline_webhook_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook"
cicd_tekton_pipeline_webhook_image_tag: "v0.26.0"
cicd_tekton_trigger_operator_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/triggers/cmd/controller"
cicd_tekton_trigger_operator_image_tag: "v0.15.0"
cicd_tekton_trigger_el_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink"
cicd_tekton_trigger_el_image_tag: "v0.15.0"
cicd_tekton_trigger_webhook_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/triggers/cmd/webhook"
cicd_tekton_trigger_webhook_image_tag: "v0.15.0"
cicd_tekton_trigger_interceptor_image_repo: "{{ gcr_image_repo }}/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors"
cicd_tekton_trigger_interceptor_image_tag: "v0.15.0"
