# Default storage class name
# It should be changed to the storage class name user want to use
# This value can be 'nfs' or 'efs-sc' provided by the hypercloud, or any other value user create
# default_storageclass_name: efs-sc
