---
- name: CI/CD Operator | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/cicd"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: CI/CD Operator | Generate Manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/cicd/{{ item.file }}"
  with_items:
    - { name: 01-tekton-pipelines, file: 01-tekton-pipelines.yml }
    - { name: 02-tekton-triggers, file: 02-tekton-triggers.yml }
    - { name: 03-tekton-triggers-interceptor, file: 03-tekton-triggers-interceptor.yml }
    - { name: 04-cicd-operator, file: 04-cicd-operator.yml }
  register: cicd_manifests
  when: inventory_hostname == groups['kube_control_plane'][0]

- name: CI/CD Operator | Apply Manifests
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/addons/cicd/{{ item.item.file }}"
    state: "latest"
    wait: true
  with_items:
    - "{{ cicd_manifests.results }}"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
  loop_control:
    label: "{{ item.item.file }}"
