---
- import_tasks: 0010-update-api-server.yml
  when:
    - dns_mode != 'none'
    - api_server_dns_cfwhn
  tags:
    - dns-policy-cfwhn

- import_tasks: update-etcd.yaml
  run_once: true
  delegate_to: "{{ groups['kube_control_plane']|first }}"
  delegate_facts: false
  tags:
    - update-etcd

- import_tasks: update-kube-controller-manager.yaml
  tags:
    - update-kube-controller-manager

- import_tasks: update-kube-scheduler.yaml
  tags:
    - update-kube-scheduler
