# check postinstall already deployed
- name: "check deployed postinstall"
  stat:
    path: "{{ kube_config_dir }}/etcd_deployed"
  register: deployed

# create postinstall etcd deployment file
- name: create file etcd deployed
  copy:
    content: "deployed"
    dest: "{{ kube_config_dir }}/etcd_deployed"
    force: no
    group: sys
    owner: root
    mode: 0555
  when: not deployed.stat.exists

# add etcd's label for prometheus
- name: update etcd | Add k8s-app label for prometheus
  lineinfile:
    firstmatch: yes
    path: '{{ kube_manifest_dir }}/etcd.yaml'
    regexp: 'k8s-app: etcd'
    insertafter: 'labels:'
    state: present
    line: '    k8s-app: etcd'
  when:
  - prometheus_k8s_app_label
  tags:
  - prometheus-k8s-app-label 

# add etcd timezone
- name: update etcd | Add etcd timezone(mountPath)
  lineinfile:
    firstmatch: yes
    state: present
    dest: '{{ kube_manifest_dir }}/etcd.yaml'
    insertafter: 'volumeMounts:'
    line: '{{ item }}'
  with_items:
    - '      name: {{ timezone_extra_volumes.name }}'
    - '    - mountPath: {{ timezone_extra_volumes.mountPath }}'
  when:
  - etcd_timezone
  - not deployed.stat.exists
  tags:
  - etcd_timezone

# add etcd timezone
- name: update etcd | Add etcd timezone(hostPath)
  lineinfile:
    firstmatch: yes
    state: present
    dest: '{{ kube_manifest_dir }}/etcd.yaml'
    insertafter: 'volumes:'
    line: '{{ item }}'
  with_items:
    - '    name: {{ timezone_extra_volumes.name }}'
    - '      path: {{ timezone_extra_volumes.hostPath }}'
    - '  - hostPath: '
  when:
  - etcd_timezone
  - not deployed.stat.exists
  tags:
  - etcd_timezone

# add host ip to etcd's command/listen-metrics-urls
- name: update etcd | Add host ip to etcd's command/listen-metrics-urls
  replace:
    path: '{{ kube_manifest_dir }}/etcd.yaml'
    regexp: '--listen-metrics-urls=http://127.0.0.1:2381'
    replace: '--listen-metrics-urls=http://127.0.0.1:2381,http://{{ ip | default(fallback_ips[inventory_hostname]) }}:2381'
  when:
  - master_ip_in_listen_metrics_urls
  - not deployed.stat.exists
  tags:
  - listen-metrics-urls

# restart etcd crio/containerd
- name: update etcd | restart etcd crio/containerd
  shell: "{{ bin_dir }}/crictl pods --name etcd -q | xargs -I% --no-run-if-empty bash -c '{{ bin_dir }}/crictl stopp % && {{ bin_dir }}/crictl rmp %'"
  register: remove_container
  retries: 10
  until: remove_container.rc == 0
  delay: 1
  when:
    - container_manager in ['crio', 'containerd']
    - inventory_hostname in groups['kube_control_plane']

# waiting for the etcd component to be running
- name: update etcd | wait for the etcd to be running
  uri:
    url: '{{ etcd_health_check_url }}'
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 1

