# Install script to update K8S control plane certificates
- name: Install script to update K8S control plane certificates
  template:
    src: update-kubeadm-cert.sh.j2
    dest: "{{ bin_dir }}/update-kubeadm-cert.sh"
    mode: '755'
  when:
    - update_cert
    - inventory_hostname in groups['kube_control_plane']

# Run script to update K8S control plane certificates
- name: Run script to update K8S control plane certificates
  shell: "{{ bin_dir }}/update-kubeadm-cert.sh all"
  when:
    - update_cert
    - inventory_hostname in groups['kube_control_plane']
