---
- name: Kiali | Find ingress Service's IP of Kiali
  command: "{{ bin_dir }}/kubectl get ingress kiali -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}'"
  changed_when: false
  register: "kiali_ip_status"
  when: 
    - kiali_ip == "0.0.0.0"

- name: Kiali | Set ingress Service IP of Kiali
  set_fact:
    kiali_ip: "{{ kiali_ip_status.stdout }}"
  when: kiali_ip_status.stdout | length != 0


- name: Kubeflow | Find Service's IP of Kubeflow
  command: "{{ bin_dir }}/kubectl get services -n istio-system istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}'"
  changed_when: false
  register: "kubeflow_ip_status"
  when: kubeflow_ip == "0.0.0.0"

- name: Kubeflow | Set Service IP of Kiali
  set_fact:
    kubeflow_ip: "{{ kubeflow_ip_status.stdout }}"
  when: kubeflow_ip_status.stdout | length != 0

# - name: gitlab | Find gitlab pod 
#   command: "{{ bin_dir }}/kubectl -n gitlab-system get pod | grep gitlab | awk '{print $1}'"
#   changed_when: false
#   register: "gitlab_pod"
#   when: gitlab_url == "http://localhost"

# - name: Kubeflow | Set Service IP of Kiali
#   set_fact:
#     kubeflow_ip: "{{ kubeflow_ip_status.stdout }}"
#   when: kubeflow_ip_status.stdout | length != 0
