---
- name: Kiali | Find ingress Service's IP of Kiali
  command: "{{ bin_dir }}/kubectl get services -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}'"
  changed_when: false
  register: "kiali_ip_status"
  when: kiali_ip | length == 0

- name: Kiali | Set ingress Service IP of Kiali
  set_fact:
    kiali_ip: "{{ kiali_ip_status.stdout }}"
  when: kiali_ip | length == 0

# - name: Kubeflow | Find ingress Service's IP of Kiali
#   command: "{{ bin_dir }}/kubectl get services -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}'"
#   changed_when: false
#   register: "kiali_ip_status"
#   when: kiali_ip | length == 0


# - name: Kiali | Set ingress Service IP of Kiali
#   set_fact:
#     kiali_ip: "{{ kiali_ip_status.stdout }}"
#   when: kiali_ip | length == 0