---
ingress_nginx_name: "ingress-nginx-shared"
ingress_nginx_controller_registry: "quay.io"
ingress_nginx_certgen_registry: "docker.io"
ingress_nginx_controller_version: "0.33.0"
ingress_nginx_certgen_version: "v1.2.2"
ingress_nginx_class: "nginx-shd"