---
- name: Registry Operator | Find ingress Service's IP
  command: "{{ bin_dir }}/kubectl get services -n {{ ingress_nginx_namespace }} {{ ingress_nginx_namespace }}-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}'"
  changed_when: false
  register: "ingress_status"
  when: registry_operator_ingress_nginx_ip | length == 0

- name: Registry Operator | Set ingress Service IP
  set_fact:
    registry_operator_ingress_nginx_ip: "{{ ingress_status.stdout }}"
  when: registry_operator_ingress_nginx_ip | length == 0
