---

- name: Clair | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/clair"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Clair | Templates list
  set_fact:
    clair_templates:
      - { name: clair-ns, file: clair-ns.yml, type: ns }
      - { name: clair-svc, file: clair-svc.yml, type: svc }
      - { name: clair-rs, file: clair-rs.yml, type: rs }
      - { name: clair-db-svc, file: clair-db-svc.yml, type: svc }
      - { name: clair-db-rs, file: clair-db-rs.yml, type: rs }

- name: Clair | Create manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/clair/{{ item.file }}"
  with_items: "{{ clair_templates }}"
  register: clair_manifests
  when: inventory_hostname == groups['kube_control_plane'][0]

- name: Clair | Apply manifests
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ clair_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ kube_config_dir }}/addons/clair/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ clair_manifests.results }}"
  when: inventory_hostname == groups['kube_control_plane'][0]

#- name: Clair | Create PVC manifests
#  template:
#    src: "{{ item.file }}.j2"
#    dest: "{{ kube_config_dir }}/addons/clair/{{ item.file }}"
#  with_items:
#    - { name: clair-pvc, file: clair-pvc.yml, type: pvc }
#  register: clair_manifests
#  when:
#    - clair_storage_class != none and clair_storage_class
#    - clair_disk_size != none and clair_disk_size
#    - inventory_hostname == groups['kube_control_plane'][0]
#
#- name: Clair | Apply PVC manifests
#  kube:
#    name: "{{ item.item.name }}"
#    namespace: "{{ clair_namespace }}"
#    kubectl: "{{ bin_dir }}/kubectl"
#    resource: "{{ item.item.type }}"
#    filename: "{{ kube_config_dir }}/addons/clair/{{ item.item.file }}"
#    state: "latest"
#  with_items: "{{ clair_manifests.results }}"
#  when:
#    - clair_storage_class != none and clair_storage_class
#    - clair_disk_size != none and clair_disk_size
#    - inventory_hostname == groups['kube_control_plane'][0]
