---
# defaults file for ai_devops
ai_devops_enabled: true

# ai_devops_install_namespace  
ai_devops_namespace: "kubeflow"
istio_namespace: "istio-system"
knative_namespace: "knative-serving"

# 1. cluster-local-gateway parameters
istio_proxyv_image_repo: "{{ docker_image_repo }}/istio/proxyv2"
istio_proxyv_image_tag: "1.3.1"

# 2. kubeflow-istio-resources parameters
gatewaySelector: ingressgateway

# 3. application parameters
application_controller_image_repo: "{{ gcr_image_repo }}/kubeflow-images-public/kubernetes-sigs/application"
application_controller_image_tag: "1.0-beta"

# 4. kubeflow-apps parameters
profiles_deployment_image_repo: "{{ gcr_image_repo }}/kubeflow-images-public/profile-controller"
profiles_deployment_image_tag: "vmaster-ga49f658f"
profiles_deployment_image_2_repo: "{{ gcr_image_repo }}/kubeflow-images-public/kfam"
profiles_deployment_image_2_tag: "vmaster-g9f3bfd00"

# 5. katib parameters
default_trial_template_image_repo: "{{ docker_image_repo }}/kubeflowkatib/mxnet-mnist"
default_trial_templage_image_tag: "v1beta1-45c5727"
default_trial_template_image_2_repo: "{{ docker_image_repo }}/kubeflowkatib/enas-cnn-cifar10-cpu"
default_trial_template_image_2_tag: "v1beta1-45c5727"
default_trial_template_image_3_repo: "{{ docker_image_repo }}/kubeflowkatib/pytorch-mnist"
default_trial_template_image_3_tag: "v1beta1-45c5727"
katib_controller_image_repo: "{{ docker_image_repo }}/kubeflowkatib/katib-controller"
katib_controller_image_tag: "v0.11.0"
katib_db_manager_image_repo: "{{ docker_image_repo }}/kubeflowkatib/katib-db-manager"
katib_db_manager_image_tag: "v0.11.0"
mysql_image_repo: "{{ docker_image_repo }}/library/mysql"
mysql_image_tag: "8"
katib_ui_image_repo: "{{ docker_image_repo }}/kubeflowkatib/katib-ui"
katib_ui_image_tag: "v0.11.0"
katib_cert_generator_image_repo: "{{ docker_image_repo }}/kubeflowkatib/cert-generator"
katib_cert_generator_image_tag: "v0.11.0"


# 6. argo parameters
executor_image_repo: "{{ docker_image_repo }}/argoproj/argoexec"
executor_image_tag: "v2.12.10"
argo_server_image_repo: "{{ docker_image_repo }}/argoproj/argocli"
argo_server_image_tag: "v2.12.10"
workflow_controller_image_repo: "{{ docker_image_repo }}argoproj/workflow-controller"
workflow_controller_image_repo: "v2.12.10"

# 7. minio parameters
minio_image_repo: "{{ gcr_image_repo }}/ml-pipeline/minio"
minio_image_tag: "RELEASE.2019-08-14T20-37-41Z-license-compliance"

# 8. notebook parameters
notebook_controller_image_repo: "{{ docker_image_repo }}/tmaxcloudck/notebook-controller-go"
notebook_controller_image_tag: "b0.1.0"
jupyter_lab_kale_image_repo: "{{ docker_image_repo }}/tmaxcloudck/jupyterlab-kale"
jupyter_lab_kale_image_tag: "b1.0.1"

# 9. pytorchjob parameters
pytorch_operator_image_repo: "{{ gcr_image_repo }}/kubeflow-images-public/pytorch-operator"
pytorch_operator_image_tag: "vmaster-g518f9c76"

# 10. tfjob parameters
tf_job_operator_image_repo: "{{ gcr_image_repo }}/kubeflow-images-public/tf_operator"
tf_job_operator_image_tag: "vmaster-gda226016"

# 11. knative parameters
queue_sidecar_image_repo: "{{ gcr_image_repo }}/knative-releases/knative.dev/serving/cmd/queue"
queue_sidecar_image_tag: "v0.14.3"
activator_image_repo: "{{ gcr_image_repo }}/knative-releases/knative.dev/serving/cmd/activator"
activator_image_tag: "v0.14.3"
autoscaler_image_repo: "{{ gcr_image_repo }}/knative-releases/knative.dev/serving/cmd/autoscaler"
autoscaler_image_tag: "v0.14.3"
controller_image_repo: "{{ gcr_image_repo }}/knative-releases/knative.dev/serving/cmd/controller"
controller_image_tag: "v0.14.3"
istio_webhook_image_repo: "{{ gcr_image_repo }}/knative-releases/knative.dev/net-istio/cmd/webhook"
istio_webhook_image_tag: "v0.14.1"
networking_istio_image_repo: "{{ gcr_image_repo }}/knative-releases/knative.dev/net-istio/cmd/controller"
networking_istio_image_tag: "v0.14.1"
webhook_image_repo: "{{ gcr_image_repo }}/knative-releases/knative.dev/serving/cmd/webhook"
webhook_image_tag: "v0.14.3"

# 12. kfserving parameters
kfserving_controller_image_repo: "{{ gcr_image_repo }}/kfserving/kfserving-controller"
kfserving_controller_image_tag: "v0.5.1"
kube_rbac_proxy_image_repo: "{{ gcr_image_repo }}/kubebuilder/kube-rbac-proxy"
kube_rbac_proxy_image_tag: "v0.4.0"
kfserving_agent_image_repo: "{{ docker_image_repo }}/kfserving/agent"
kfserving_agent_image_tag: "v0.5.1"
alibi_explainer_image_repo: "{{ docker_image_repo }}/kfserving/alibi-explainer"
alibi_explainer_image_tag: "v0.5.1"
aix_explainer_image_repo: "{{ docker_image_repo }}/kfserving/aix-explainer"
aix_explainer_image_tag: "v0.5.1"
art_explainer_image_repo: "{{ docker_image_repo }}/kfserving/art-explainer"
art_explainer_image_tag: "v0.5.1"
tensorflow_image_repo: "{{ docker_image_repo }}/tensorflow/serving"
tensorflow_image_tag: "1.14.0"
tensorflow_image_gpu_tag: "1.14.0-gpu"
onnx_image_repo: "{{ mcr_image_repo }}/onnxruntime/server"
onnx_image_tag: "v1.0.0"
sklearn_image_repo: "{{ gcr_image_repo }}/kfserving/sklearnserver"
sklearn_image_tag: "v0.5.1"
mlserver_image_repo: "{{ docker_image_repo }}/seldonio/mlserver"
mlserver_image_tag: "0.2.1"
xgboost_image_repo: "{{ gcr_image_repo }}/kfserving/xgbserver"
xgboost_image_tag: "v0.5.1"
pytorch_server_image_repo: "{{ gcr_image_repo }}/kfserving/pytorchserver"
pytorch_server_image_tag: "v0.5.1"
pytorch_server_image_gpu_tag: "v0.5.1-gpu"
torchserve_kfs_image_repo: "{{ docker_image_repo }}/kfserving/torchserve-kfs"
torchserve_kfs_image_tag: "0.3.0"
torchserve_kfs_image_gpu_tag: "0.3.0-gpu"
triton_image_repo: "{{ nvcr_image_repo }}/nvidia/tritonserver"
triton_image_tag: "20.08-py3"
pmml_image_repo: "{{ docker_image_repo }}/kfserving/pmmlserver"
pmml_image_tag: "v0.5.1"
lgb_image_repo: "{{ docker_image_repo }}/kfserving/lgbserver"
lgb_image_tag: "v0.5.1"
storage_initializer_image_repo: "{{ gcr_image_repo }}/kfserving/storage-initializer"
storage_initializer_image_tag: "v0.5.1"

 
                          