---
# defaults file for efk
efk_enabled: true

# namespace for efk
efk_namespace: "kube-logging"

# parameters for elasticsearch
efk_es_replicas: 3
efk_es_image_repo: "{{ elastic_image_repo }}/elasticsearch/elasticsearch"
efk_es_image_tag: "7.2.0"
efk_busybox_image_repo: "busybox"
efk_busybox_image_repo: "1.32.0"
efk_es_volume_size: "50Gi"

# parameters for kibana
efk_kibana_service_type: "NodePort"
efk_kibana_replicas: 1
efk_kibana_image_repo: "{{ elastic_image_repo }}/kibana/kibana"
efk_kibana_image_tag: "7.2.0"

# parameters for fluentd
efk_fluentd_image_repo: "fluent/fluentd-kubernetes-daemonset"
efk_fluentd_image_tag: "v1.4.2-debian-elasticsearch-1.1"
