---
# tasks file for hypercloud
- name: Hypercloud | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/hypercloud"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]


- name: Hypercloud | Create config dir
  file:
    path: "{{ kube_config_dir }}/addons/hypercloud/config"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]      


- name: Hypercloud | Create pki dir
  file:
    path: "{{ kube_config_dir }}/addons/hypercloud/pki"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]      


- name: Hypercloud | Create html dir
  file:
    path: "{{ kube_config_dir }}/addons/hypercloud/html"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]      


- name: Hypercloud | Generate Manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/hypercloud/{{ item.file }}"
  with_items:
    - { name: init, file: 01_init.yaml }
    - { name: postgres-create, file: 02_postgres-create.yaml }
    - { name: hypercloud-api-server, file: 03_hypercloud-api-server.yaml }
    - { name: default-role, file: 04_default-role.yaml }
    - { name: "hypercloud-single-operator-v{{ hypercloud_single_operator_image_tag }}", file: "hypercloud-single-operator-v{{ hypercloud_single_operator_image_tag }}.yaml" }
    - { name: kafka-secret, file: kafka-secret.yaml }
  register: hypercloud_manifests
  when: 
    - inventory_hostname == groups['kube_control_plane'][0]


- name: Hypercloud | Generate Manifests CAPI Template
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/hypercloud/{{ item.file }}"
  with_items:
    - { name: "hypercloud-multi-operator-v{{ hypercloud_multi_operator_image_tag }}", file: "hypercloud-multi-operator-v{{ hypercloud_multi_operator_image_tag }}.yaml" }
    - { name: "capi-aws-template-v{{ hypercloud_hpcd_template_version }}", file: "capi-aws-template-v{{ hypercloud_hpcd_template_version }}.yaml" }
#    - { name: "capi-vsphere-template-v{{ hypercloud_hpcd_template_version }}", file: "capi-vsphere-template-v{{ hypercloud_hpcd_template_version }}.yaml" }
  register: hypercloud_manifests_CAPI_template     
  when: 
    - inventory_hostname == groups['kube_control_plane'][0]
    - hypercloud_hpcd_mode == "multi"
  ignore_errors: yes
  

- name: Hypercloud | Generate Config
  template:
    src: "config/{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/hypercloud/config/{{ item.file }}"
  with_items:
    - { name: audit-policy, file: audit-policy.yaml }
    - { name: audit-webhook-config, file: audit-webhook-config }
    - { name: audit-webhook-config.template, file: audit-webhook-config.template }
    - { name: gen-audit-config, file: gen-audit-config.sh }
    - { name: webhook-configuration, file: webhook-configuration.yaml }
  register: hypercloud_config
  when: 
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Hypercloud | Generate Html
  template:
    src: "html/{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/hypercloud/html/{{ item.file }}"
  with_items:
    - { name: cluster-invitation.html, file: cluster-invitation.html }
  register: hypercloud_manifests
  when: 
    - inventory_hostname == groups['kube_control_plane'][0]


- name: Hypercloud | Make Namespace hypercloud5-system
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/addons/hypercloud/{{ item }}"
    state: "latest"
    wait: true
  with_items:
    - "01_init.yaml"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]


- name: Hypercloud | Apply Single-Operator
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/addons/hypercloud/{{ item }}"
    state: "latest"
    wait: true
  with_items:
    - "hypercloud-single-operator-v{{ hypercloud_hpcd_single_operator_version }}.yaml"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]


- name: Hypercloud | Check Html Config Exists
  shell: "{{ bin_dir }}/kubectl get configmap html-config -n hypercloud5-system"
  register: html_config_result
  failed_when: >
    (html_config_result.stderr != '') or
    (html_config_result.rc == 1)
  ignore_errors: yes
    

- name: Hypercloud | Create Html
  ansible.builtin.shell: |
    sudo chmod +777 {{ kube_config_dir }}/addons/hypercloud/html/cluster-invitation.html
    {{ bin_dir }}/kubectl create configmap html-config --from-file={{ kube_config_dir }}/addons/hypercloud/html/cluster-invitation.html -n hypercloud5-system
  args:
    chdir: "{{ kube_config_dir }}/addons/hypercloud/html"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - html_config_result.failed

- name: Hypercloud | Check Hypercloud Kafka Secret Exists
  shell: "{{ bin_dir }}/kubectl get secret hypercloud-kafka-secret -n hypercloud5-system"
  register: hypercloud_kafka_secret_result
  failed_when: >
    (hypercloud_kafka_secret_result.stderr != '') or
    (hypercloud_kafka_secret_result.rc == 1)
  ignore_errors: yes

- name : Hypercloud | Create Hypercloud Kafka Secret
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/addons/hypercloud/{{ item }}"
    state: "latest"
    wait: true
  with_items:
    - "kafka-secret.yaml"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - hypercloud_kafka_secret_result.failed

- name: Hypercloud | Apply Hypercloud Api Server
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/addons/hypercloud/{{ item }}"
    state: "latest"
    wait: true
  with_items:
    #- "01_init.yaml"
    - "02_postgres-create.yaml"
    - "03_hypercloud-api-server.yaml"
    - "04_default-role.yaml"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]


- name: Hypercloud | Wait for Hypercloud Api Server Pod become available
  ansible.builtin.shell: |
    {{ bin_dir }}/kubectl wait -n hypercloud5-system --for=condition=Ready pods --selector hypercloud5=api-server --timeout=1200s
  register: hypercloud5_api_server_status
  until: ("condition met" in hypercloud5_api_server_status.stdout)
  retries: 400
  when:
    - inventory_hostname == groups['kube_control_plane'][0]


- name: Hypercloud | Create Audit & Webhook Config
  ansible.builtin.shell: |
    sudo chmod +x *.sh 
    sudo ./gen-audit-config.sh
    sudo cp audit-policy.yaml /etc/kubernetes/ssl/
    sudo cp audit-webhook-config /etc/kubernetes/ssl/
    {{ bin_dir }}/kubectl apply -f webhook-configuration.yaml
  args:
    chdir: "{{ kube_config_dir }}/addons/hypercloud/config"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]


- name: Hypercloud | Check that the OIDC settings Already Registered
  shell: cat /etc/kubernetes/manifests/kube-apiserver.yaml | grep audit-webhook
  register: oidc_audit_webhook_registered
  failed_when: >
    (oidc_audit_webhook_registered.stderr != '') or
    (oidc_audit_webhook_registered.rc == 1)
  ignore_errors: yes


- name: Hypercloud | Modify Kubernetes Api Server Manifest
  ansible.builtin.shell: |
    sudo cp /etc/kubernetes/manifests/kube-apiserver.yaml .
    yq e '.spec.containers[0].command += "--audit-webhook-mode=batch"' -i ./kube-apiserver.yaml
    yq e '.spec.containers[0].command += "--audit-policy-file=/etc/kubernetes/ssl/audit-policy.yaml"' -i ./kube-apiserver.yaml
    yq e '.spec.containers[0].command += "--audit-webhook-config-file=/etc/kubernetes/ssl/audit-webhook-config"' -i ./kube-apiserver.yaml
    mv -f ./kube-apiserver.yaml /etc/kubernetes/manifests/kube-apiserver.yaml
  args:
    chdir: "{{ kube_config_dir }}/addons/hypercloud/"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - oidc_audit_webhook_registered.failed


- name: Hypercloud | Wait for Kubernetes Api Server Pod become available
  ansible.builtin.shell: |
    {{ bin_dir }}/kubectl wait -n kube-system --for=condition=Ready pods --selector component=kube-apiserver --timeout=1200s
  register: kube_api_server_status
  until: ("condition met" in kube_api_server_status.stdout)
  retries: 400
  when:
    - inventory_hostname == groups['kube_control_plane'][0]


- name: Hypercloud | Check Whether Audit Config Exists
  stat:
    path: "{{ kube_config_dir }}/ssl/audit-webhook-config"
  register: audit_config_exists


- name: Hypercloud | Fetch Audit Config from master1
  run_once: yes
  fetch: src={{ kube_config_dir }}/ssl/{{ item }} dest=./inventory/mycluster/ flat=yes
  with_items:
    - audit-policy.yaml
    - audit-webhook-config
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - audit_config_exists.stat.exists


- name: Hypercloud | Copy Audit Config to All Master /etc/kubernetes/ssl
  copy: src=./inventory/mycluster/{{ item }} dest=/etc/kubernetes/ssl/
  with_items:
    - audit-policy.yaml
    - audit-webhook-config
  when:
    - inventory_hostname in groups['kube_control_plane']
    - not audit_config_exists.stat.exists


- name: Hypercloud | Modify Multi Operator Config
  ansible.builtin.shell: |
    FILE=("hyperauth.crt" "audit-webhook-config" "audit-policy.yaml")
    PARAM=("\${HYPERAUTH_CERT}" "\${AUDIT_WEBHOOK_CONFIG}" "\${AUDIT_POLICY}")
    for i in ${!FILE[*]}
    do
      sudo awk '{print "          " $0}' /etc/kubernetes/ssl/${FILE[$i]} > ./${FILE[$i]}
      sudo sed -e '/'${PARAM[$i]}'/r ./'${FILE[$i]}'' -e '/'${PARAM[$i]}'/d' -i ./capi-*-template-v{{ hypercloud_hpcd_template_version }}.yaml
      rm -f ./${FILE[$i]}
    done
#    sed -i 's#'hypercloud5-api-server-service.hypercloud5-system.svc/audit'#'hypercloud5-api-server-service.{{ hostvars[groups['kube_node'][0]]['ansible_host'] }}.nip.io'\/audit\/${Namespace}\/${clusterName}#g' ./capi-*-template-v{{ hypercloud_hpcd_template_version }}.yaml
  args:
    chdir: "{{ kube_config_dir }}/addons/hypercloud/"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - hypercloud_hpcd_mode == "multi"


- name: Hypercloud | Apply Multi Operator
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/addons/hypercloud/{{ item }}"
    state: "latest"
    wait: true
  with_items:
    - "hypercloud-multi-operator-v{{ hypercloud_hpcd_multi_operator_version }}.yaml"
    - "capi-aws-template-v{{ hypercloud_hpcd_template_version }}.yaml"
#    - "capi-vsphere-template-v{{ hypercloud_hpcd_template_version }}.yaml"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - hypercloud_hpcd_mode == "multi"


- name: Hypercloud | Generate Manifests Hypercloud Multi Agent
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/hypercloud/{{ item.file }}"
  with_items:
    - { name: "01_federate-namespace.yaml", file: "01_federate-namespace.yaml" }
    - { name: "02_federate-clusterRoleBinding.yaml", file: "02_federate-clusterRoleBinding.yaml" }
    - { name: "03_federate-deployment.yaml", file: "03_federate-deployment.yaml" }
  register: hypercloud_manifests_multi_agent
  when: 
    - inventory_hostname == groups['kube_control_plane'][0]
    - hypercloud_hpcd_mode == "multi"


- name: Hypercloud | Apply Hypercloud Multi Agent
  kube:
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/addons/hypercloud/{{ item }}"
    state: "latest"
    wait: true
  with_items:
    - "01_federate-namespace.yaml"
    - "02_federate-clusterRoleBinding.yaml"
    - "03_federate-deployment.yaml"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
    - hypercloud_hpcd_mode == "multi"
