---
# if do not use httpd repository, local repository file is moved to hosts. 
- import_tasks: copy_files_repo.yml
  when: files_repo is defined and httpd_repo_address is not defined

# if use httpd repository, it sets repository setting to k8s hosts. 
- import_tasks: set_httpd_repo.yml
  when: httpd_repo_address is defined
