---
- name: copy required files | Ensure directory exist 
  file:
    path: "{{ files_repo | regex_replace('^file://', '') }}"
    state: directory

- name: copy required files | Copy files
  copy: 
    src: "{{ files_repo | regex_replace('^file://', '') }}/"
    dest: "{{ files_repo | regex_replace('^file://', '') }}/"

- import_tasks: set_httpd_repo.yml
  when: httpd_repo_url is defined
