- name: Find existing repositories
  find: 
    paths: /etc/yum.repos.d
    file_type: file
  register: all_repositories

- name: Remove existing repositories
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ all_repositories.files }}"

- name: Add httpd repository setting to hosts
  template:
    src: files-repo.repo.j2
    dest: /etc/yum.repos.d/files-repo.repo
    mode: '0644'
    owner: root
    group: root
